# Generated by Django 6.0.1 on 2026-03-25 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizes',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quizes', to='quiz_bot.customuser'),
            preserve_default=False,
        ),
    ]
