# Generated by Django 6.0.1 on 2026-01-10 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizanswers',
            name='is_correct',
        ),
        migrations.RemoveField(
            model_name='quizanswers',
            name='question',
        ),
        migrations.AddField(
            model_name='quizanswers',
            name='correct_answers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizanswers',
            name='not_answered',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizanswers',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz_bot.quizes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizanswers',
            name='total_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='quizanswers',
            name='wrong_answers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quizanswers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_answers', to='quiz_bot.customuser'),
        ),
    ]
