services:
  django:
    build: .
    command: python manage.py runserver
    volumes:
      - .:/app
      - ./static:/app/staticfiles:/staticfiles
    env_file:
      - .env
    expose:
      - "8000"

  bot:
    build: .
    command: python manage.py bot
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - django
