version: "3.9"

services:
  django:
    build: .
    container_name: quiz_django
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"

  bot:
    build: .
    container_name: quiz_bot
    command: python manage.py bot
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - django
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
