version: "3.9"

services:
  django:
    build: .
    container_name: zakovat_django
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: always

  bot:
    build: .
    container_name: zakovat_bot
    command: sh -c "python manage.py migrate && python manage.py bot"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - django
    restart: always
